version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
      args:
        VUE_APP_BACKEND_URL: ${VITE_APP_BACKEND_URL}
    ports:
      - "8080:80"
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    restart: always