"""Initial Migration

Revision ID: 8df5a3e388ec
Revises:
Create Date: 2024-07-23 14:29:08.213819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8df5a3e388ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filaments',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('color', sa.String(length=60), nullable=True),
                    sa.Column('material', sa.String(length=60), nullable=True),
                    sa.Column('manufacturer', sa.String(length=60), nullable=True),
                    sa.Column('approximate_left', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('printers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.Column('model', sa.String(length=60), nullable=True),
                    sa.Column('image', sa.String(length=300), nullable=True),
                    sa.Column('manufacturer', sa.String(length=60), nullable=True),
                    sa.Column('bookings', postgresql.ARRAY(sa.Integer()), nullable=True),
                    sa.Column('filaments', postgresql.ARRAY(sa.Integer()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.String(length=20), nullable=False),
                    sa.Column('firstname', sa.String(length=60), nullable=True),
                    sa.Column('surname', sa.String(length=60), nullable=True),
                    sa.Column('mail', sa.String(length=80), nullable=True),
                    sa.Column('department', sa.String(length=60), nullable=True),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bookings',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user', sa.String(length=20), nullable=True),
                    sa.Column('printer', sa.Integer(), nullable=True),
                    sa.Column('from', sa.TIMESTAMP(), nullable=True),
                    sa.Column('to', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['printer'], ['printers.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('printers')
    op.drop_table('filaments')
    # ### end Alembic commands ###
